{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.glassmc",
    "module": "kiln",
    "version": "0.8.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "kiln-0.8.5.jar",
          "url": "kiln-0.8.5.jar",
          "size": 98045,
          "sha512": "71643e430b03405ca4f94b30ffcb23f4ef0247daca65806cad818f41f2b0187df02d55d3c2d214b3b822f65a3c2b125683b158e9c76d729cfe035908796439d3",
          "sha256": "f8cd07a337b28a183f187d35e7d24b051367550b1b5296b08427e0a090c9ca21",
          "sha1": "471222278489ef98500c17395a34bdb290f67c4e",
          "md5": "c7b46293fd620bdd85036914f5974108"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20220320"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "com.github.jezza",
          "module": "toml",
          "version": {
            "requires": "1.2-java-8"
          }
        },
        {
          "group": "com.github.johnrengelman",
          "module": "shadow",
          "version": {
            "requires": "7.1.2"
          }
        },
        {
          "group": "com.github.fabricmc",
          "module": "tiny-mappings-parser",
          "version": {
            "requires": "750be4e739"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "kiln-0.8.5.jar",
          "url": "kiln-0.8.5.jar",
          "size": 98045,
          "sha512": "71643e430b03405ca4f94b30ffcb23f4ef0247daca65806cad818f41f2b0187df02d55d3c2d214b3b822f65a3c2b125683b158e9c76d729cfe035908796439d3",
          "sha256": "f8cd07a337b28a183f187d35e7d24b051367550b1b5296b08427e0a090c9ca21",
          "sha1": "471222278489ef98500c17395a34bdb290f67c4e",
          "md5": "c7b46293fd620bdd85036914f5974108"
        }
      ]
    }
  ]
}
