{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.glassmc",
    "module": "kiln",
    "version": "0.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "kiln-0.8.2.jar",
          "url": "kiln-0.8.2.jar",
          "size": 97323,
          "sha512": "87a9b8ca281e3349fb0ae625ba6fa6f064af9498152103b5f58f6dc7028803225b35e562e0e45e132b62ff1ad700fdba1e078a24e2f96a1e8c0f2ac368377687",
          "sha256": "bc8aea6bc71b1326e728f6f7a0f86cfe5b90e265a0feb4086963dd167cd9a8cf",
          "sha1": "94cbb61b0f962e01d56d41bc1545f3cfe817c3ad",
          "md5": "ca440df75515fa52b66431332d181a38"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20211205"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "com.github.jezza",
          "module": "toml",
          "version": {
            "requires": "1.2-java-8"
          }
        },
        {
          "group": "com.github.johnrengelman",
          "module": "shadow",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "com.github.fabricmc",
          "module": "tiny-mappings-parser",
          "version": {
            "requires": "750be4e739"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "kiln-0.8.2.jar",
          "url": "kiln-0.8.2.jar",
          "size": 97323,
          "sha512": "87a9b8ca281e3349fb0ae625ba6fa6f064af9498152103b5f58f6dc7028803225b35e562e0e45e132b62ff1ad700fdba1e078a24e2f96a1e8c0f2ac368377687",
          "sha256": "bc8aea6bc71b1326e728f6f7a0f86cfe5b90e265a0feb4086963dd167cd9a8cf",
          "sha1": "94cbb61b0f962e01d56d41bc1545f3cfe817c3ad",
          "md5": "ca440df75515fa52b66431332d181a38"
        }
      ]
    }
  ]
}
