{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.glassmc",
    "module": "kiln",
    "version": "0.6.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "kiln-0.6.18.jar",
          "url": "kiln-0.6.18.jar",
          "size": 68723,
          "sha512": "63c6f056b74c03b9bd0757547f36fd196a4959daed1bd8fd45332f4648892bf64914f6f9cc714aeea0f0f8b383c5dcb78ac03d0d4aca49b20c89849e9da0570d",
          "sha256": "ecafda3a5173d11ec814bd849aa369dea8e9aeb71c91171e2c8ceac2dabcb8bf",
          "sha1": "7a7ce23cae8ea26317b6f291c5e26fb135e9d014",
          "md5": "ae197b9932e74ea33b63aed4c49b609d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20211205"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "com.github.jezza",
          "module": "toml",
          "version": {
            "requires": "1.2-java-8"
          }
        },
        {
          "group": "com.github.johnrengelman",
          "module": "shadow",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "com.github.fabricmc",
          "module": "tiny-mappings-parser",
          "version": {
            "requires": "750be4e739"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "kiln-0.6.18.jar",
          "url": "kiln-0.6.18.jar",
          "size": 68723,
          "sha512": "63c6f056b74c03b9bd0757547f36fd196a4959daed1bd8fd45332f4648892bf64914f6f9cc714aeea0f0f8b383c5dcb78ac03d0d4aca49b20c89849e9da0570d",
          "sha256": "ecafda3a5173d11ec814bd849aa369dea8e9aeb71c91171e2c8ceac2dabcb8bf",
          "sha1": "7a7ce23cae8ea26317b6f291c5e26fb135e9d014",
          "md5": "ae197b9932e74ea33b63aed4c49b609d"
        }
      ]
    }
  ]
}
