{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.glassmc",
    "module": "kiln",
    "version": "0.6.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "kiln-0.6.18.jar",
          "url": "kiln-0.6.18.jar",
          "size": 68948,
          "sha512": "a773085fc944adbbfad71f19139c91b0e94d083811ae4ad3001794b0d5ad904861a518ce6aaa362434b349be4b2c28215e4cc3d67084b02bc915440a135dbe8e",
          "sha256": "c73f86008debe157e6c1df9df7f4800ce188cbcffa98e09ab5a4e360f9a1115e",
          "sha1": "4ac3427c85a0e09f7db00eab2d34eaa7f90fde23",
          "md5": "fb1d3ec92421a2aee436cd5633beea90"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20211205"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "com.github.jezza",
          "module": "toml",
          "version": {
            "requires": "1.2-java-8"
          }
        },
        {
          "group": "com.github.johnrengelman",
          "module": "shadow",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "com.github.fabricmc",
          "module": "tiny-mappings-parser",
          "version": {
            "requires": "750be4e739"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "kiln-0.6.18.jar",
          "url": "kiln-0.6.18.jar",
          "size": 68948,
          "sha512": "a773085fc944adbbfad71f19139c91b0e94d083811ae4ad3001794b0d5ad904861a518ce6aaa362434b349be4b2c28215e4cc3d67084b02bc915440a135dbe8e",
          "sha256": "c73f86008debe157e6c1df9df7f4800ce188cbcffa98e09ab5a4e360f9a1115e",
          "sha1": "4ac3427c85a0e09f7db00eab2d34eaa7f90fde23",
          "md5": "fb1d3ec92421a2aee436cd5633beea90"
        }
      ]
    }
  ]
}
