{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.glassmc",
    "module": "kiln",
    "version": "0.6.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "kiln-0.6.18.jar",
          "url": "kiln-0.6.18.jar",
          "size": 68693,
          "sha512": "8b8af143dd910cd704d243c647cf10a2409257cc51a0ed2bc63f711c878a2793920f9b904c0907d2c6d1851ecbb36ccd7ad901b932c39cd196ba6ef1ad066581",
          "sha256": "84391dfe2060b00ede213b64d1018acc28909816e3311c7134827574f8df4500",
          "sha1": "f214e5675b20d23b38a207f16311a0439cd57ad9",
          "md5": "d0d3af7fed8a4f43a09491e9953426ce"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20211205"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "com.github.jezza",
          "module": "toml",
          "version": {
            "requires": "1.2-java-8"
          }
        },
        {
          "group": "com.github.johnrengelman",
          "module": "shadow",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "com.github.fabricmc",
          "module": "tiny-mappings-parser",
          "version": {
            "requires": "750be4e739"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "kiln-0.6.18.jar",
          "url": "kiln-0.6.18.jar",
          "size": 68693,
          "sha512": "8b8af143dd910cd704d243c647cf10a2409257cc51a0ed2bc63f711c878a2793920f9b904c0907d2c6d1851ecbb36ccd7ad901b932c39cd196ba6ef1ad066581",
          "sha256": "84391dfe2060b00ede213b64d1018acc28909816e3311c7134827574f8df4500",
          "sha1": "f214e5675b20d23b38a207f16311a0439cd57ad9",
          "md5": "d0d3af7fed8a4f43a09491e9953426ce"
        }
      ]
    }
  ]
}
