{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.glassmc",
    "module": "kiln",
    "version": "0.9.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "kiln-0.9.3.jar",
          "url": "kiln-0.9.3.jar",
          "size": 125401,
          "sha512": "f6c7b9a41a78ba97ffd4b17168506d517a02fc2bb4b7ce6163bcbbc68ab972fb4c43ec487f8c9c7925e9c49c31b3a1eb98e1a784864122bde9479967cc43e861",
          "sha256": "06d290c238cbf6fe4ecaa3ff5c5ac90a0f2954767ff9076f8569ba3de8669cb6",
          "sha1": "ebafe10aea7e4fd70bcd97c80d9a3c146a78b95d",
          "md5": "43c19f9d2c406f8246f8073972534319"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20220320"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "com.github.jezza",
          "module": "toml",
          "version": {
            "requires": "1.2-java-8"
          }
        },
        {
          "group": "com.github.johnrengelman",
          "module": "shadow",
          "version": {
            "requires": "7.1.2"
          }
        },
        {
          "group": "com.github.fabricmc",
          "module": "tiny-mappings-parser",
          "version": {
            "requires": "750be4e739"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jboss.windup.decompiler",
          "module": "decompiler-fernflower",
          "version": {
            "requires": "5.3.0.Final"
          }
        }
      ],
      "files": [
        {
          "name": "kiln-0.9.3.jar",
          "url": "kiln-0.9.3.jar",
          "size": 125401,
          "sha512": "f6c7b9a41a78ba97ffd4b17168506d517a02fc2bb4b7ce6163bcbbc68ab972fb4c43ec487f8c9c7925e9c49c31b3a1eb98e1a784864122bde9479967cc43e861",
          "sha256": "06d290c238cbf6fe4ecaa3ff5c5ac90a0f2954767ff9076f8569ba3de8669cb6",
          "sha1": "ebafe10aea7e4fd70bcd97c80d9a3c146a78b95d",
          "md5": "43c19f9d2c406f8246f8073972534319"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kiln-0.9.3-sources.jar",
          "url": "kiln-0.9.3-sources.jar",
          "size": 58785,
          "sha512": "3c6a40b5f9913e175e362cd3503cfe52ed4b0f3637bf4050b496d3cb76f7f549c00c70f2293cbce5e0cee77f282c08c11592914e781f91171b8ad034b25a1962",
          "sha256": "975783e025047878a33167c3aec408f9acab36efab720465677ee01156f63bf3",
          "sha1": "c16f830e89bb910f25850178e7ea1521deabce5e",
          "md5": "625d2f2283cfa409cb0932d9762db198"
        }
      ]
    }
  ]
}
