{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.glassmc",
    "module": "kiln",
    "version": "0.7.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "kiln-0.7.7.jar",
          "url": "kiln-0.7.7.jar",
          "size": 92930,
          "sha512": "19d0f71da26cedf8842b9918fc4d2d915eba52387034e38f7a5fd34bed79b2372d4e015326c898a71e027d28b36fd2dd885bc4c103b70557df16cb2fdcf95058",
          "sha256": "717f73f92eef27f4d1ddc20912ea6fa37bcb79f2f861b85c355965550bf6b50f",
          "sha1": "1cb0d6f44c6240a852ce27a1f07808d9d497f825",
          "md5": "29aa564d0c2374c057c09a9610074c62"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20211205"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "com.github.jezza",
          "module": "toml",
          "version": {
            "requires": "1.2-java-8"
          }
        },
        {
          "group": "com.github.johnrengelman",
          "module": "shadow",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "com.github.fabricmc",
          "module": "tiny-mappings-parser",
          "version": {
            "requires": "750be4e739"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "kiln-0.7.7.jar",
          "url": "kiln-0.7.7.jar",
          "size": 92930,
          "sha512": "19d0f71da26cedf8842b9918fc4d2d915eba52387034e38f7a5fd34bed79b2372d4e015326c898a71e027d28b36fd2dd885bc4c103b70557df16cb2fdcf95058",
          "sha256": "717f73f92eef27f4d1ddc20912ea6fa37bcb79f2f861b85c355965550bf6b50f",
          "sha1": "1cb0d6f44c6240a852ce27a1f07808d9d497f825",
          "md5": "29aa564d0c2374c057c09a9610074c62"
        }
      ]
    }
  ]
}
