{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.glassmc",
    "module": "kiln",
    "version": "0.7.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "kiln-0.7.12.jar",
          "url": "kiln-0.7.12.jar",
          "size": 92420,
          "sha512": "833027d1d6e597adb8d8cab79b65fe90c505164f7b57048f3901150466615a17d93eb49f41f7e88c39abad2cce5695333bbc022f7e5826e96fbd521e0b6fdf2b",
          "sha256": "3ecfcd0869dd811374ef3a045e9437ba5e6684a8f3b23ef0ac732a04660ac0df",
          "sha1": "3cc1749aafe450ef13bec5b25c12f8a58b30f92a",
          "md5": "af4533bace241a1cc8bf5fe429c951ce"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20211205"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "com.github.jezza",
          "module": "toml",
          "version": {
            "requires": "1.2-java-8"
          }
        },
        {
          "group": "com.github.johnrengelman",
          "module": "shadow",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "com.github.fabricmc",
          "module": "tiny-mappings-parser",
          "version": {
            "requires": "750be4e739"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "kiln-0.7.12.jar",
          "url": "kiln-0.7.12.jar",
          "size": 92420,
          "sha512": "833027d1d6e597adb8d8cab79b65fe90c505164f7b57048f3901150466615a17d93eb49f41f7e88c39abad2cce5695333bbc022f7e5826e96fbd521e0b6fdf2b",
          "sha256": "3ecfcd0869dd811374ef3a045e9437ba5e6684a8f3b23ef0ac732a04660ac0df",
          "sha1": "3cc1749aafe450ef13bec5b25c12f8a58b30f92a",
          "md5": "af4533bace241a1cc8bf5fe429c951ce"
        }
      ]
    }
  ]
}
