{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.glassmc",
    "module": "mixin",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mixin-1.0.jar",
          "url": "mixin-1.0.jar",
          "size": 14274,
          "sha512": "a8696de8648201f7e35ddc4b771e71f30727bdf851b80484391a2d136cfcee3bb9bdbb0bd0950ab9ca3589b3d6cae5b3c0e6732480c3686391f55c94a93e4021",
          "sha256": "040984d14c8f1324eb7b1b1a2ef85fdb2d8fbd5573f7289df83d327749845260",
          "sha1": "f803ba9b9da11ebe1ddf26298bbd76609d23cd1a",
          "md5": "76e98d721e220e7fec1acbb0b4187ea8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.glassmc",
          "module": "loader",
          "version": {
            "requires": "v0.8.3"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.0.1-jre"
          }
        },
        {
          "group": "org.spongepowered",
          "module": "mixin",
          "version": {
            "requires": "0.8.3"
          }
        }
      ],
      "files": [
        {
          "name": "mixin-1.0.jar",
          "url": "mixin-1.0.jar",
          "size": 14274,
          "sha512": "a8696de8648201f7e35ddc4b771e71f30727bdf851b80484391a2d136cfcee3bb9bdbb0bd0950ab9ca3589b3d6cae5b3c0e6732480c3686391f55c94a93e4021",
          "sha256": "040984d14c8f1324eb7b1b1a2ef85fdb2d8fbd5573f7289df83d327749845260",
          "sha1": "f803ba9b9da11ebe1ddf26298bbd76609d23cd1a",
          "md5": "76e98d721e220e7fec1acbb0b4187ea8"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mixin-1.0-all.jar",
          "url": "mixin-1.0-all.jar",
          "size": 4825570,
          "sha512": "7e5ab0baf4193987639702fe3203a62f645a049afb8883111c67fa37456f11710e5b7fd155ebeb1766257b1d890df7ed112d9d7896274c679a5fe79672f96f44",
          "sha256": "e60e142652147a7b0264fdb6af4e294613b90115991fbe639f7ccf8f5928570d",
          "sha1": "b7e7330beaf9ab813e8866f418e26e4d45c42d15",
          "md5": "2aafd4f9ab633227493b6658daed2848"
        }
      ]
    }
  ]
}
