{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.glassmc",
    "module": "mixin",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mixin-1.0.jar",
          "url": "mixin-1.0.jar",
          "size": 14274,
          "sha512": "543f8c3168c157fba1dab42e429b0c94c80599ce93b6c9595d55fd8abb858eaab8eea59da99b6604acc1fcb95801f43f253e4108b1e32eaf26a453e5b892e6cf",
          "sha256": "f9b57021d4bd057f6c75401a61e6a48d44882515c5340f39ff358859376d046b",
          "sha1": "dcbefc808f1708b503a45a5e0aa5482e120aeb3d",
          "md5": "1790903e45f42fcde477fee5f3e1f58e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.glassmc",
          "module": "loader",
          "version": {
            "requires": "v0.8.3"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.0.1-jre"
          }
        },
        {
          "group": "org.spongepowered",
          "module": "mixin",
          "version": {
            "requires": "0.8.3"
          }
        }
      ],
      "files": [
        {
          "name": "mixin-1.0.jar",
          "url": "mixin-1.0.jar",
          "size": 14274,
          "sha512": "543f8c3168c157fba1dab42e429b0c94c80599ce93b6c9595d55fd8abb858eaab8eea59da99b6604acc1fcb95801f43f253e4108b1e32eaf26a453e5b892e6cf",
          "sha256": "f9b57021d4bd057f6c75401a61e6a48d44882515c5340f39ff358859376d046b",
          "sha1": "dcbefc808f1708b503a45a5e0aa5482e120aeb3d",
          "md5": "1790903e45f42fcde477fee5f3e1f58e"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mixin-1.0-all.jar",
          "url": "mixin-1.0-all.jar",
          "size": 4825570,
          "sha512": "6f4aa3e4139f2493a9a91bcf4548203cd098b9f5be0313250943102f42cc94460153c22c697c766867c8778e2518c58e7dfbb399cd4199a0428b24ca050aae51",
          "sha256": "483dc217283709535b69766cf568807452c17056b9573f7cda568f84e8d51423",
          "sha1": "447f6c71d7db76c9f2fbe23dbf3b530eace8ceb5",
          "md5": "16b2d2af3c76d6cba7d2544fa7726e8a"
        }
      ]
    }
  ]
}
