{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.glassmc",
    "module": "kiln",
    "version": "0.8.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "kiln-0.8.8.jar",
          "url": "kiln-0.8.8.jar",
          "size": 102531,
          "sha512": "2925ddc0cb5dd0cd967e5f9059f644d0fd5e71338db67836c5c34e57e69de81a3cbb4471dd823554ca45ac3c7ae2cd1b99f133f9c5c7c244d92c3467d64114b6",
          "sha256": "b039ff7b599a3919a01f70474ea367e35c72b9df2ef7fd593f711c8773c17ec1",
          "sha1": "6e83f23ef83d8e492f200de9004e8d96d8d65d4b",
          "md5": "3da25db9207488e47f57e65658bb66c7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20220320"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "com.github.jezza",
          "module": "toml",
          "version": {
            "requires": "1.2-java-8"
          }
        },
        {
          "group": "com.github.johnrengelman",
          "module": "shadow",
          "version": {
            "requires": "7.1.2"
          }
        },
        {
          "group": "com.github.fabricmc",
          "module": "tiny-mappings-parser",
          "version": {
            "requires": "750be4e739"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "kiln-0.8.8.jar",
          "url": "kiln-0.8.8.jar",
          "size": 102531,
          "sha512": "2925ddc0cb5dd0cd967e5f9059f644d0fd5e71338db67836c5c34e57e69de81a3cbb4471dd823554ca45ac3c7ae2cd1b99f133f9c5c7c244d92c3467d64114b6",
          "sha256": "b039ff7b599a3919a01f70474ea367e35c72b9df2ef7fd593f711c8773c17ec1",
          "sha1": "6e83f23ef83d8e492f200de9004e8d96d8d65d4b",
          "md5": "3da25db9207488e47f57e65658bb66c7"
        }
      ]
    }
  ]
}
