{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.glassmc",
    "module": "kiln",
    "version": "0.8.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "kiln-0.8.3.jar",
          "url": "kiln-0.8.3.jar",
          "size": 97975,
          "sha512": "685fdbab4d08c28fceb2e4f7aa39dbd6061d2bd3be0979f327ae64017acd743fc92c9968524ce9e90e664d02f25589d1739c9327eefcad18d92b26401e556514",
          "sha256": "2ebd35ce36a74fab66ba493d9888e608901bdd3a7e59129217973feb8e0d186c",
          "sha1": "8c3767ed56434362a78a1d15fc356b8ae60031e3",
          "md5": "46b4dace424bad64fafa1b397d3cbc0b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20211205"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "com.github.jezza",
          "module": "toml",
          "version": {
            "requires": "1.2-java-8"
          }
        },
        {
          "group": "com.github.johnrengelman",
          "module": "shadow",
          "version": {
            "requires": "7.1.2"
          }
        },
        {
          "group": "com.github.fabricmc",
          "module": "tiny-mappings-parser",
          "version": {
            "requires": "750be4e739"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "kiln-0.8.3.jar",
          "url": "kiln-0.8.3.jar",
          "size": 97975,
          "sha512": "685fdbab4d08c28fceb2e4f7aa39dbd6061d2bd3be0979f327ae64017acd743fc92c9968524ce9e90e664d02f25589d1739c9327eefcad18d92b26401e556514",
          "sha256": "2ebd35ce36a74fab66ba493d9888e608901bdd3a7e59129217973feb8e0d186c",
          "sha1": "8c3767ed56434362a78a1d15fc356b8ae60031e3",
          "md5": "46b4dace424bad64fafa1b397d3cbc0b"
        }
      ]
    }
  ]
}
